### PR TITLE
Simplify bookmark impl by exposing internal values

### PR DESCRIPTION
**Pull request by zhenlineo**
This makes serialization of the bookmark easier to end users.
End users could serialize and deserialize bookmark in whatever way they like using `Set<String> values`

Bookmark is defined as follows:
```
Bookmark {
Set<String> values(); // can be used to serialize bookmark
static Bookmark parse(Set<String> values); // can be used to deserialize bookmark
boolean isEmpty();
}
```

### CODE REVIEW

**Review by michael-simons — CHANGES_REQUESTED** [review]
I'd remove `static Bookmark merge(Iterable<String> bookmarks);` to avoid confusion.  It's not needed with `.parse` and `.merge` in combination and clutters API (at least to me, maybe that's personal taste).

I'm also a bit confused as I thought we spoke about dumping the bookmarks as `byte[]` from the driver.

**Comment by zhenlineo** [comment]
@michael-simons Very good input on the `merge` methods. Would you think this API will be good enough for your use case if we have `merge` methods removed?

We talked about `toBytes`, but it is not very idiomatic to Javascript, where most of objects are directly visible to users. .Net driver gives this solution which gives me some new thoughts. The original purpose to hide Bookmark implementation was to prevent users from using the bookmark content, however if users (OGM and/or Fabric) need to use the content anyway, I see fewer points to hide it.

**Review by PetrJanouch — APPROVED** [review]

**Comment by michael-simons** [comment]
Thanks, Zhen. I'd only remove the `static Bookmark merge(Iterable<String> bookmarks);` 

With the Strings is totally fine with me this way.

**Review by michael-simons — APPROVED** [review]
LGTM! Thanks for your work on that.

**Pull request merged**
