### PR TITLE
Upgrade to Netty 4.1.36, support native compilation

### PR DESCRIPTION
**Pull request by michael-simons**
Ping @shelajev @jexp 

That is an ongoing effort to

- Use Netty 4.1.36, that brings automatic substitutions for the native GraalVM
- Add some shims to help those with our shading

Netty added substitutions and meta data for native compilation on the
GraalVM in version 4.1.36, which should be a drop in for 4.1.22.

See the related discussion here: https://github.com/netty/netty/pull/8963.
Those substitutions works also when Netty is shaded. 

I confirmed this with a patched version of my Quarkus-Neo4j-extension
(see https://github.com/quarkusio/quarkus/tree/master/extensions/neo4j),
in which I can remove all the manual substitutions as well.

I also have a  Helidon project (https://github.com/michael-simons/helidon-test), which now natively compiles, but get's stuck with

`2019.07.20 18:22:14 WARNING org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelId !thread!: Failed to find the current process ID from ''; using a random value: 1210464143`

All necessary options have been configured that SSL works on Graal OOTB. However, when not relying on infrastructure like Quarkus, one has to configure Libssl during start like this `-Djava.library.path=$GRAALVM_HOME/jre/lib -Djavax.net.ssl.trustStore=$GRAALVM_HOME/jre/lib/security/cacerts `

### CODE REVIEW

**Comment by zhenlineo** [comment]
Can you rebase this work on https://github.com/neo4j/neo4j-java-driver/pull/631?

**Comment by michael-simons** [comment]
> Can you rebase this work on #631?

I'll probably copy it over. Did the Netty upgrade made it to master already?

**Comment by zhenlineo** [comment]
Yes. go ahead.

**Comment by michael-simons** [comment]
Closing in favour of #634 .

**Pull request closed without merging**
