### PR TITLE
Fix typo & clean import

### PR DESCRIPTION
**Pull request by fbiville**
Nothing big :)

### CODE REVIEW

**Comment by zhenlineo** [comment]
Oh, thanks a lot. Could you rebase this pr and I will then merge it :)

**Comment by fbiville** [comment]
Done :)

**Comment by jakewins** [comment]
Hey - it may seem a bit silly for a typo fix like this, but for legal reasons would you mind just quickly signing the Neo4j CLA? It's just a 2-min email, and that way you'll be a whitelisted contributor for all the neo repos:

http://neo4j.com/docs/stable/cla.html

**Comment by fbiville** [comment]
And also done :)

**Pull request merged**
