### PR TITLE
osgify artefact MANIFEST.MF (jar + sources)

### PR DESCRIPTION
**Pull request by CrystalMethod**
when applied the generated artefacts (jar + source-jar) will contain valid OSGi manifest headers to be consumed in OSGi environments / Eclipse

```
Manifest-Version: 1.0
Bundle-Description: Access to the Neo4j graph database through Java
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0
Package: org/neo4j/driver
Bundle-SymbolicName: org.neo4j.driver
Implementation-Version: 1.1-SNAPSHOT-${git.commit.id.abbrev}
Archiver-Version: Plexus Archiver
Bundle-ManifestVersion: 2
Include-Resource: license-header.txt=src/main/resources/license-header
 .txt
Import-Package: javax.net.ssl,javax.xml.bind,org.neo4j.driver.v1.excep
 tions;version="[1.1,2)",org.neo4j.driver.v1.exceptions.value;version=
 "[1.1,2)",org.neo4j.driver.v1.summary;version="[1.1,2)",org.neo4j.dri
 ver.v1.types;version="[1.1,2)",org.neo4j.driver.v1.util;version="[1.1
 ,2)"
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
Tool: Bnd-3.2.0.201605172007
Export-Package: org.neo4j.driver.v1;version="1.1.0",org.neo4j.driver.v
 1.exceptions;version="1.1.0",org.neo4j.driver.v1.exceptions.value;ver
 sion="1.1.0",org.neo4j.driver.v1.summary;version="1.1.0",org.neo4j.dr
 iver.v1.types;version="1.1.0",org.neo4j.driver.v1.util;version="1.1.0
 "
Bundle-Name: Neo4j Java Driver
Bundle-Version: 1.1.0.v20161129-2034
Created-By: Apache Maven Bundle Plugin
Build-Jdk: 1.8.0_112
```

### CODE REVIEW

**Comment by zhenlineo** [comment]
Hi, thanks very much for the PR. Would you mind to sign [CLA](https://neo4j.com/developer/cla/) so that we could merge your PR?

Also pls note that we might not maintain this osgi support. But you are always welcome to contribute and fix the plugin definition and `osgi.bnd` file.

**Comment by dkrizic** [comment]
Funny, I was just about the create the same PR...

**Comment by CrystalMethod** [comment]
@zhenlineo the CLA was signed and sent to cla@... as I plan to actively use the bundle in Eclipse I will try to support it as much as possible.

@dkrizic feel free to verify / comment the changes.. is the ``Bundle-SymbolicName`` sufficient?

**Comment by dkrizic** [comment]
I prepared OSGi for Neo4j-OGM (see https://github.com/neo4j/neo4j-ogm/pull/256). The Java Driver was the missing part. From Neo4j-OGM I reference the Java Driver as "neo4j-java-driver". You use "org.neo4j.driver". So we need to change either.

**Comment by CrystalMethod** [comment]
@dkrizic Sorry, I didn't know your efforts regarding Neo4j-OGM. I haven't set my heart on that symbolic name (``org.neo4j.driver``) but I think its a common practice to use a FQN starting with the origin domain.

You actually are/were referencing the fragment host as follows:

```xml
 <Fragment-Host>org.neo4j.ogm-api</Fragment-Host>
```

So a ``Bundle-SymbolicName: org.neo4j.driver`` or ``org.neo4j.java-driver`` would be a good counterpart; where the ``java-`` prefix seems to me to be superfluous.

But anyway, the name should follow the same pattern all over the Neo4j bundle universe.

**Comment by dkrizic** [comment]
This is the list of all the Bundle-SymblicNames i use:

- Neo4j Java Driver (org.neo4j.driver.neo4j-java-driver)
- Neo4j-OGM Compiler (org.neo4j.ogm-compiler)
- Neo4j-OGM HTTP Driver (org.neo4j.ogm-http-driver)
- Neo4j-OGM Core (org.neo4j.ogm-core)
- Neo4j-OGM BOLT Driver (org.neo4j.ogm-bolt-driver)	
- Neo4j-OGM API (org.neo4j.ogm-api)
- Neo4j-OGM ResourceResolver Equinox (org.neo4j.ogm-equinox-resolver)

So I took the Maven groupId and artifactId to have a 1:1 mapping. I fully agree that all names should be consistent, so feel free to recommend something.

**Comment by CrystalMethod** [comment]
Then I have misunderstood your comment above. I had understood that your where preferring ``neo4j-java-driver`` as the Bundle-SymbolicName. But I'm fine with ``org.neo4j.driver.neo4j-java-driver``. And the 1:1 mapping is a recognisable pattern.

**Comment by dkrizic** [comment]
Ok, then change it :-)

**Comment by CrystalMethod** [comment]
@dkrizic Done. I encourage you to create also source-bundles, so we can easily set up an Eclipse p2  repository providing runtime + sdk features.

**Comment by dkrizic** [comment]
Never done that. A bundle that contains the source code?

**Comment by lutovich** [comment]
Hi @CrystalMethod!

Unfortunately I can't see your CLA in the inbox. Could you please re-send it?
I'll merge this PR then.

Thanks a lot!

**Comment by lutovich** [comment]
Hello @CrystalMethod, @dkrizic.

We still did not receive a signed CLA so I can't merge this PR :(
Please re-send it, maybe email got bounced.
Thanks in advance.

**Comment by dkrizic** [comment]
Hi @lutovich,

can you just point me to the CLA?

**Comment by lutovich** [comment]
Hi @dkrizic, to be able to merge these changes we will need a signed CLA from @CrystalMethod.
See http://neo4j.com/developer/cla/ for further information.
Additional information on contributing code is found at
http://neo4j.com/developer/contributing-code/

**Comment by dkrizic** [comment]
You have my CLA now, even I did not make the Pull Request, but maybe some things in future.

**Comment by CrystalMethod** [comment]
I've been sending the CLA yesterday.

**Comment by zhenlineo** [comment]
@CrystalMethod Hi I do not think we have received your CLA, but we do recevied @dkrizic's CLA.
@CrystalMethod Could you confirm that you were sending the email to `cla at neotechnology.com`? Do you mind also CC me `zhen.li at neotechnology.com` when you send a new one?

We are planing a release soon. It might be great if we could include this one into next release.
Cheers,
Zhen

**Comment by CrystalMethod** [comment]
Here is the part from the log file (only modified the address). So far I did not get any bounce. I will resend it with your address in CC.

```Jan  4 11:23:10 mail postfix/smtp[12518]: 05DCA166B: to=<cla AT neotechnology.com>,
 relay=127.0.0.1[127.0.0.1]:10024, delay=1.2, delays=0.17/0/0.01/1, dsn=2.0.0, s
tatus=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as
2026A1689)
Jan  4 11:23:10 mail postfix/smtp[12545]: 2026A1689: to=<cla AT neotechnology.com>,
 relay=ASPMX.L.GOOGLE.com[66.102.1.27]:25, delay=0.65, delays=0.08/0.02/0.25/0.2
9, dsn=2.0.0, status=sent (250 2.0.0 OK 1483528989 5si81040050wjz.60 - gsmtp)
```

**Comment by zhenlineo** [comment]
@CrystalMethod Thanks I got your CLA!

**Pull request merged**
